version: '3'

services:
    database:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        image: redis
    flower:
        image: localhost:5000/whatson
        command: make flower
        ports:
            - 5555:5553
        expose:
            - 5553
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - ./app:/app
        links:
            - database
            - redis
        environment:
            PGDATABASE: postgres
            PGUSER: postgres
            PGPASSWORD: password
            PGHOST: database
            PGPORT: 5432
            CELERY_HOST: redis
            REDIS_HOST: redis
            DJANGO_SETTINGS_MODULE: whatson.settings.dev
            FLOWER_USER: user
            FLOWER_PASSWORD: password

    worker:
        image: localhost:5000/whatson
        command: make worker-local
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        links:
            - database
            - redis
        environment:
            PGDATABASE: postgres
            PGUSER: postgres
            PGPASSWORD: password
            PGHOST: database
            PGPORT: 5432
            CELERY_HOST: redis
            REDIS_HOST: redis
            DJANGO_SETTINGS_MODULE: whatson.settings.dev
            # Read from .env
            GEOCODING_API_KEY: $GEOCODING_API_KEY
    web:
        image: localhost:5000/whatson
        command: make web-local
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
          - ./app:/app
          - build:/app/build
          - node_modules:/app/node_modules
        links:
            - database
            - redis
            - worker
            - webpack
            - flower
        environment:
            PGDATABASE: postgres
            PGUSER: postgres
            PGPASSWORD: password
            PGHOST: database
            PGPORT: 5432
            CELERY_HOST: redis
            REDIS_HOST: redis
            DJANGO_SETTINGS_MODULE: whatson.settings.dev
            # Read from .env
            GEOCODING_API_KEY: $GEOCODING_API_KEY
    webpack:
        image: localhost:5000/whatson
        command: make webpack
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
            - build:/app/build

volumes:
    postgres-data:
    node_modules:
    build:
