version: "3"

services:
  database:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  redis:
    image: redis
  flower:
    image: localhost:5000/whatson
    command: make flower-local
    ports:
      - 5555:5553
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    links:
      - database
      - redis
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      CELERY_HOST: redis
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: whatson.settings.dev
      FLOWER_USER: user
      FLOWER_PASSWORD: password

  worker:
    image: localhost:5000/whatson
    command: make worker-local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    links:
      - database
      - redis
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      CELERY_HOST: redis
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: whatson.settings.dev
      # Read from .env
      GEOCODING_API_KEY: $GEOCODING_API_KEY
  web:
    image: localhost:5000/whatson
    command: make web-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    links:
      - database
      - redis
      - worker
      - flower
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      CELERY_HOST: redis
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: whatson.settings.dev
      # Read from .env
      GEOCODING_API_KEY: $GEOCODING_API_KEY

  test:
    image: localhost:5000/whatson
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      CELERY_HOST: redis
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: whatson.settings.dev

volumes:
  postgres-data:
