# Generated by Django 2.0.4 on 2018-05-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0003_auto_20180502_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(),
        ),
    ]
