# Generated by Django 2.0.5 on 2018-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0004_auto_20180505_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scraper', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
