# Generated by Django 2.0.5 on 2018-05-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0006_auto_20180506_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('TRIVIA', 'Trivia')], default='MUSIC', max_length=15),
            preserve_default=False,
        ),
    ]
