# Generated by Django 2.0.5 on 2018-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0010_auto_20180515_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_search',
            field=models.BooleanField(default=False),
        ),
    ]
